import './globals.css'
import type { Metadata } from 'next'
import { CartProvider } from './checkout/CartContext';
import Header from './components/Header';
import Footer from './components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <CartProvider>
    <html lang="en">
        <body className="container font-main m-auto bg-gray-200 text-primary-200 box-border">
        <Header />

          {children}
        <Footer />
        </body>
    </html>
    </CartProvider>

  )
}
