import './globals.css'
import type { Metadata } from 'next'
import { CartProvider } from './checkout/CartContext';
import Header from './components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <CartProvider>
    <html lang="en">
        <body className="font-main grid grid-cols-6 align-start items-start bg-gray-200 text-primary-200 box-border">
        <Header />
          {children}
        <h1 className="col-span-6 text-center">Footer</h1>
        </body>
    </html>
    </CartProvider>

  )
}
